version: 2.1

orbs:
   aws-cli: circleci/aws-cli@2.0.3
   
jobs:
    configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory main.yml --private-key newkey.pem
workflows:
  DeploymentFlow:
    jobs:
      - configure_infrastructure
