version: 2.1

orbs:
   aws-cli: circleci/aws-cli@2.0.3
   
jobs:
    configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
                # You can get this ID in the section where you registered the SSH Key
                fingerprints: ["67:30:7c:cb:09:25:88:93:0a:06:84:09:5c:a8:cd:a7"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory main.yml
workflows:
  DeploymentFlow:
    jobs:
      - configure_infrastructure
