# Exercise: Config and Deployment
configure_infrastructure: 
  docker:
    - image: 
  steps:
    - checkout
    - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX"] 
    - run:
        name: Install Ansible
        command: |
          apk add --update ansible
    - run:
        name: Run Playbook and Configure server
        command: |
          ansible-playbook -i inventory main.yml
