version: 2.1

orbs:
   aws-cli: circleci/aws-cli@2.0.3
   
jobs:
    configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
                # You can get this ID in the section where you registered the SSH Key
                fingerprints: ["76:39:28:6c:ea:d4:05:5d:30:cb:f8:b9:13:9d:1c:96"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory main.yml
workflows:
  DeploymentFlow:
    jobs:
      - configure_infrastructure
