version: 2.1

orbs:
   aws-cli: circleci/aws-cli@2.0.3
   
jobs:
    configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
                # You can get this ID in the section where you registered the SSH Key
                fingerprints: ["8b:f1:8e:8c:d7:9e:d6:5e:07:6a:26:e0:36:ef:f3:92"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory main.yml
workflows:
  DeploymentFlow:
    jobs:
      - configure_infrastructure
