version: 2.1

orbs:
   aws-cli: circleci/aws-cli@2.0.3
   
jobs:
    configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
                # You can get this ID in the section where you registered the SSH Key
                fingerprints: ["be:4e:c4:82:dc:ad:1c:c3:52:1b:83:ea:55:df:9b:1e:43:dc:f0:33"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory main.yml
workflows:
  DeploymentFlow:
    jobs:
      - configure_infrastructure
